spring:
   datasource:
      name: isadb
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
         filters: stat
         driver-class-name: com.mysql.jdbc.Driver
         url: jdbc:mysql://127.0.0.1:3306/intergratesystem?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
         username: root
         password: 123456
         initial-size: 1
         min-idle: 1
         max-active: 20
         max-wait: 60000
         time-between-eviction-runs-milles: 60000
         min-evictable-idle-time-millis: 300000
         validation-query: SELECT 'X'
         test-while-idle: true
         test-on-borrow: false
         test-on-return: false
         pool-prepared-statements: false
         max-pool-prepared-statement-per-connection-size: 20
   application:
      name: api-pay
   rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
   redis:
      host: 127.0.0.1
      port: 6379
      timeout: 5000
      password: 123456
      #redis数据库索引，默认0
      database: 0  
      pool:
         # 连接池最大连接数（使用负值表示没有限制）
         max-active: 8
         # 连接池最大阻塞等待时间（使用负值表示没有限制）
         max-wait: -1
         # 连接池中的最大空闲连接
         max-idle: 8
         # 连接池中的最小空闲连接
         min-idle: 0
         # 连接超时时间（毫秒）
         timeout: 5000

mybatis:
   mapper-locations: classpath:mapper/*.xml
eureka:
   client:
      serviceUrl:
         defaultZone: http://adminUser:User123@127.0.0.1:8001/eureka/
server:
   port: 8008
payment:
  appid: d7b73d6916ed47bb8b0e0bd352dc1e3e
  mer-private: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCfXF/AC6mrS5yrZICmLuyrgVjdBMBFd2T2g+qjAxj/KDRx3cqZO/7kEgnW0Z+iYL8cAn6qz46Uu2kE5uF0mCWt+A2qelF53grTMmwd6zmIE/+RAV7DXCxmtHo+oBGDt+tWuQQfRv3OJioqLkTq+Cep/8LkbPGLfCVcwJO5UnU7aVQhokGaf2lk+bBNHOfkZ7toH5HUNx3wH5UZwEi6wS06BiW5/aARrw6ZDJNZVcIsHRLwOzn3peLIKxgFID3kRMlXUaDNclLZ4zsHHf4ewtSMg+jx4ieDrozLy56OWaHr19j1JZuNwGEuv3RPKURNZJh0V9ZtC8SD7utBo1Bvlf/pAgMBAAECggEAaJsPMxW0wv84EP1AwVUt/4pBVZtHxpGP0Y1YGLbw0pSGkHPhCGLsdrMsiDlDiyfsaqtskBz8X78BObmAJrO0kBSyi8QM9Wz+OBHyDFWahytxZ7K5jI1Vi/lOAQu7U3YH4f5CqXFFKuu8Y8HJdV99UcbUHHMyvre4IsE6drycvWjl5R4XnXNBdsR2B+jYV0NqCRLzcWoQqBPH9wUkS3eZ2+fGZ1elY3+BT62v5N1jXYi1aJjDTjwQVo5vvjBzCdHbvNzigDYJt14NKAsq9J9Qzr5nFn7dQpuzBnrlDTYURW8xG9a+ssWfsLLtHsNR3E5UwJgtp0haUTfjcIoc7WrRAQKBgQDTM9UEH/zyaxdOoDkugiJo/4j/zpR5sn+vXXns/gZn3mBKe8zNKR/oNJBHlHg3/+8u0Xqe0ZhnSQJoIJcc/7uUU5OWhGrs+BvPR0hwd6e6svgdYl8WJ3ztBXdmsuyFzRk/jGnAbwKNfYFb0pN8GCNynMmEXD+3iPTpEPz5I69QiQKBgQDBKZJ9KVKk55qMx/qFOVSQ9ILDSv7ZhhwCHcRiPmxXtd11m4YQyNwN1pNN9iqkxfwWtOEuf3THq4MUL00VPUUUDfHBxgL3C3dUxD3p3lcSOG5npXJ3ZAgHoMePfqtdZ2bZwW0g+udNOY4iwnszqjesd/9ZhnafX8JVmEA9RS2cYQKBgG978ruErx6/jMQCK2zzYHqQOJ7fStyabnABJbUFuhfl+GoYw1iglqkZ5fcC1hqpTHYoOVPQS2Rp041ndpzmGPwIyeUv7Mk9hmB5vjEv2CfjBLluDcdB/N2YfxiE5fkS9HrpAYGEl5JcZ4Yyt4tPqpZ7UJw/nZqh/rVwNDjGr2oRAoGBAIS59BZclpUJL4EcyF9SjXEtEczvcz40kHpDyfVXv0plhM6TFwPhgJNhpcYkKBkgkZ9omnJA0hWBHIh6GBVIDHdDPaNQVCk8j7qHPaO9S0cRz4sYfBbdfUcAix9mgomjy2BFMJ9AyD6gFbJ8v/s4MxknOyZg5pGMUxRNkZaIOlcBAoGAf3YQT2Dat2Dt9l6L3pGHntRMoA4fGm1D73ixN7heIfZA15ALibfDME4qukGA6/sp77t+tu/nWZNdE42/QZHAl95/j3K0gwBDVyLXM42DJIkJJqQIpqE+zfvAZJBd3HF57vqevrE36DGntxEXAyKUASyAiKPYXyp75g84znY/7mk=
  sec-public: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqIh4dbuxTOA63kTTQDNa6wOvbqAe28N/zd4e1c913Fc1F16vKQ/vaxpeocYf7yBnuEyQZoEkBOoQQcLeTLXvyTSyvz4wLcqwmlvIhH37pFs+MLWb/ovZ3nbd1L15RNpGNR59pnUSwSKkjwsbgtFng/ptMWZwUkv11egs+2UjpsltHtaEkw/w2Ai0N8JZTqaFdCnqZGkht4CSVQKOMZrAeF4AD1Siwfk0PqsFGQeJh1/iMdEA7+6P/s2K+OZjT0833nsM5MSoPOHJO4Y3mA+95KFLt30icJGNXm2U/jN4ykD6HPG4X0G8J2g8SuhB86YIOeSQB53afArB2ayfievz5QIDAQAB
  connecttimeout: 200000
  readtimeout: 200000
  redistimeout: 3600
filght: 
  mythicalanimals: http://118.190.0.224:6065/api #http://openapi.c2b168.net/api/
  agentId: 21909251257107887
  key: a7aee17b049e8db4
train: 
  housekeeper: http://train.rsscc.com
  merchantId: ydyc_test
  signKey: b1772f4866fe4b669df96c307d9b1ebf
YinQi: 
   RequestUrl: http://39.106.229.137:8080
