order:
  yunhengServerCallBack: http://264529pa28.zicp.vip/api/api-pay/merchantPayment/paymentNotice
#订单批量导入地址
orderimp: 
   fileURL: src/main/resources/template
   fileName: orderimp.xls
YinQi: 
   RequestUrl: http://39.106.229.137:8080/bankAccountInfoQuery/getCurrentAccountInfo
filght: 
  agentId: 21909251257107887
  key: a7aee17b049e8db4
  mythicalanimals: http://118.190.0.224:6065/api #http://openapi.c2b168.net/api/
train: 
  housekeeper: http://train.rsscc.com
  merchantId: ydyc_test
  signKey: b1772f4866fe4b669df96c307d9b1ebf
  occupyCallBack: http://264529pa28.zicp.vip/api/api-order/train/occupyNotice
  ticketCallBack: http://264529pa28.zicp.vip/api/api-order/train/ticketIssue
  retreatCallBack: http://264529pa28.zicp.vip/api/api-order/train/returnTicketNotice
  determineCallBack: http://264529pa28.zicp.vip/api/api-order/train/determineChangeNotice
