#端口-8007
server:
   port: 8007
#应用名称 - springcloud-zuul-swagger2
spring: 
   application:
      name: springcloud-zuul-swagger2
   redis:
      host: 127.0.0.1
      port: 6379
      timeout: 5000
      password: 123456
      #redis数据库索引，默认0
      database: 0  
      pool:
         # 连接池最大连接数（使用负值表示没有限制）
         max-active: 8
         # 连接池最大阻塞等待时间（使用负值表示没有限制）
         max-wait: -1
         # 连接池中的最大空闲连接
         max-idle: 8
         # 连接池中的最小空闲连接
         min-idle: 0
         # 连接超时时间（毫秒）
         timeout: 5000
#服务注册
eureka:
   client:
      serviceUrl:
         defaultZone: http://adminUser:User123@127.0.0.1:8001/eureka/
      registerWithEureka: true
      fetchRegistry: true
   instance:
      hostname: springcloud-zuul-swagger2
zuul:
   prefix: /api
   sensitive-headers: 
   ribbon: 
      ReadTimeout: 60000 
      ConnectTimeout: 60000 
      hystrix: 
         command: 
            default: 
               execution: 
                  isolation: 
                     thread: 
                        timeoutInMilliseconds: 60000
   routes: 
      api-admin:
         path: /api-admin/**
         url: http://127.0.0.1:8055
      api-cms:
         path: /api-cms/**
         url: http://127.0.0.1:8010
      api-order:
         path: /api-order/**
         url: http://127.0.0.1:8006
      api-pay:
         path: /api-pay/**
         url: http://127.0.0.1:8008
      api-middle: 
         path: /api-middle/**
         url: http://127.0.0.1:8009

      
         
